version: '3.8'

services:
  config-server:
    image: 626635448599.dkr.ecr.eu-north-1.amazonaws.com/config-server:latest
    ports:
      - "8888:8888"
    networks:
      - backend

  service-registry:
    image: 626635448599.dkr.ecr.eu-north-1.amazonaws.com/service-registry:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - backend

  authentication-service:
    image: 626635448599.dkr.ecr.eu-north-1.amazonaws.com/authentication-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - service-registry
    networks:
      - backend

  course-management-service:
    image: 626635448599.dkr.ecr.eu-north-1.amazonaws.com/course-management-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - service-registry
    networks:
      - backend

  api-gateway:
    image: 626635448599.dkr.ecr.eu-north-1.amazonaws.com/api-gateway:latest
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - authentication-service
      - course-management-service
    networks:
      - backend

networks:
  backend: